services:
  - type: web
    name: northwind-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    plan: free
    region: oregon
